### PR TITLE
Add algolia search to Docusaurus website

### PR DESCRIPTION
**Pull request by maoo**

### CODE REVIEW

**Review by robmoffat — APPROVED** [review]
works for me!

**Comment by robmoffat** [comment]
Would be good to get some other maintainers to review before merging.

**Comment by bingenito** [comment]
I find the results very confusing since they include all versions of the API (for example, search for 'addContextListener'.  I'm not sure it makes sense to only index the latest version so maybe it points to the need of different page titles?

**Comment by kriswest** [comment]
Could turn on contextual search, which will filter to the currently displayed version: https://docusaurus.io/docs/search#contextual-search

Otherwise, its a case of customisation and prominently displaying the version, and/or using custom facet filters. Probably best to try contextual search first as its easy to flip on

**Comment by robmoffat** [comment]
let's give it a whirl.  Just made the change

**Comment by bingenito** [comment]
> let's give it a whirl. Just made the change

+1 on this way.

**Review by bingenito — APPROVED** [review]

**Review by kriswest — APPROVED** [review]
LGTM - it does a good job of breaking down the results into the major sections and filtering to a particular version (currently selected version) is working.

**Comment by robmoffat** [comment]
yeah this looks good - merge?

**Comment by kriswest** [comment]
sure - will leave the joy or pushing the button to you ;-)

**Comment by kriswest** [comment]
Too late, pushed the button myself

**Comment by kriswest** [comment]
Thanks for the PR @maoo and @robmoffat

**Pull request merged**
