### PR TITLE
Move to Netlify for Production Site means this is no longer required

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by kriswest** [comment]
Are these also defunct @robmoffat or are they used in the netlify build:
https://github.com/finos/FDC3/blob/fde406329286f7f8b1f013d2ca948df8d9713261/website/package.json#L7-L8

**Comment by kriswest** [comment]
> Are these also defunct @robmoffat or are they used in the netlify build:
> 
> https://github.com/finos/FDC3/blob/fde406329286f7f8b1f013d2ca948df8d9713261/website/package.json#L7-L8

Maintainers can no longer see or work on the the build set-up, so you'd have to answer the above @robmoffat

**Review by kriswest — CHANGES_REQUESTED** [review]
Actually hold - the fdc3-workbench isn't working for me: https://deploy-preview-925--fdc3.netlify.app/toolbox/fdc3-workbench
ANd fdc3-explained is missing assets: https://deploy-preview-925--fdc3.netlify.app/toolbox/fdc3-explained

**Comment by kriswest** [comment]
The HTML is present but none of the built static assets @robmoffat 
image

**Comment by kriswest** [comment]
The appD spec is also broken: https://deploy-preview-925--fdc3.netlify.app/schemas/2.0/app-directory.html

These were all things dealt with by the `prepublish-gh-pages` which npm script: 

```
"prepublish-gh-pages": "npm run copy-appd && npm run copy-schemas && npm run copy-workbench",
```

which would auto-run before `publish-gh-pages` due to its naming. Clearly it needs incorporating into the netlify build - I can't see how that's set-up so can't comment on the precise fix @robmoffat.

**Comment by robmoffat** [comment]
> The appD spec is also broken: https://deploy-preview-925--fdc3.netlify.app/schemas/2.0/app-directory.html

This link works for me.  I'm backing out the trailing slash thing as I suspect this is what is breaking the workbench.  Will see when the preview builds.

**Review by kriswest — APPROVED** [review]
LGTM

**Comment by robmoffat** [comment]
> LGTM

What about the broken links to explained and workbench?

**Comment by kriswest** [comment]
Fixed 'em, it was a problem with `cpy-cli`

https://fdc3.finos.org/toolbox/fdc3-workbench
https://fdc3.finos.org/toolbox/fdc3-explained/

**Pull request merged**
