### PR TITLE
Modify generate-type-predicates to only include interfaces that have …

### PR DESCRIPTION
**Pull request by Roaders**
## Describe your change

Modification of the generate-type-predicates code to build unions types of interfaces not based on the interface name but based on the `type` declared in the interface. If `type` extends the `RequestMessageType` union then the interface is included in the `RequestMessage` union

## Contributor License Agreement

- [x] I acknowledge that a contributor license agreement is required and that I have one in place or will seek to put one in place ASAP.

## Review Checklist

- [ ] **Issue**: If a change was made to the FDC3 Standard, was an issue linked above?
- [ ] **CHANGELOG**: Is a *CHANGELOG.md* entry included?
- [ ] **API changes**: Does this PR include changes to any of the FDC3 APIs (`DesktopAgent`, `Channel`, `PrivateChannel`, `Listener`, `Bridging`)?
  - [ ] **Docs & Sources**: If yes, were both documentation (/docs) and sources updated?<br/>
        *JSDoc comments on interfaces and types should be matched to the main documentation in /docs*
  - [ ] **Conformance tests**: If yes, are conformance test definitions (/toolbox/fdc3-conformance) still correct and complete?<br/>
        *Conformance test definitions should cover all **required** aspects of an FDC3 Desktop Agent implementation, which are usually marked with a **MUST** keyword, and  optional features (**SHOULD** or **MAY**) where the format of those features is defined*
  - [ ] **Schemas**: If yes, were changes applied to the Bridging and FDC3 for Web protocol schemas?<br/>
        *The Web Connection protocol and Desktop Agent Communication Protocol schemas must be able to support all necessary aspects of the Desktop Agent API, while Bridging must support those aspects necessary for Desktop Agents to communicate with each other*
    - [ ] If yes, was code generation (`npm run build`) run and the results checked in?<br/>
        *Generated code will be found at `/src/api/BrowserTypes.ts` and/or `/src/bridging/BridgingTypes.ts`*
- [ ] **Context types**: Were new Context type schemas created or modified in this PR?
  - [ ] Were the [field type conventions](https://fdc3.finos.org/docs/context/spec#field-type-conventions) adhered to?
  - [ ] Was the `BaseContext` schema applied via `allOf` (as it is in existing types)?
  - [ ] Was a `title` and `description` provided for all properties defined in the schema?
  - [ ] Was at least one example provided?
  - [ ] Was code generation (`npm run build`) run and the results checked in?<br/>
        *Generated code will be found at `/src/context/ContextTypes.ts`*
- [ ] **Intents**: Were new Intents created in this PR?
  - [ ] Were the [intent name prefixes](https://fdc3.finos.org/docs/intents/spec#intent-name-prefixes) and other [naming conventions & characteristics](https://fdc3.finos.org/docs/intents/spec#naming-conventions) adhered to?
  - [ ] Was the new intent added to the list in the [Intents Overview](https://fdc3.finos.org/docs/intents/spec#standard-intents)?

---

THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS CORPORATE CONTRIBUTOR LICENSE AGREEMENT.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by Roaders** [comment]
Have pushed some updates.

- This should no longer duplicate code. It removes any existing statements of the same name before writing
- This removes the interfaces for `AppRequestMessage`, `AgentResponseMessage` and `AgentEventMessage` and replaces them with the generated unions

I still have to create the additional `validated` type predicate which won't take long in the morning. Do we want to remove the constants? I'm afraid I didn't understand @robmoffat explanation of what they were for.

**Comment by Roaders** [comment]
Hmmmm.... the diff is now huge... Could this just be because I deleted BrowserTypes and regenerated with the functions in a different order?

**Comment by Roaders** [comment]
> 
> ```ts
> public onMessage(message: AppRequestMessage): void{
>     switch(message){
>          case: isRaiseIntentRequest(message):
>                 ...
>                 break;
>         case isRaiseIntentForContextRequest(message):
>                 ...
>                 break;
>         default:
>                 ...
>                 console.log(`Unknown message type encountered: ` + message.type);
>     }
> ```

@kriswest is the above valid typescript? I had never seen a switch statement like that (switching on the object then using type predicates for the cases). When I try it I get compile errors:

```ts
//this is fine
if (isAddIntentListenerRequest(message)) {
    return this.onAddIntentListenerRequest(message, sourceApp);
}

switch (message) {
    // this gives a compile error:
    // Type 'boolean' is not comparable to type 'AddContextListenerRequest | BroadcastRequest | CreatePrivateChannelRequest | FindInstancesRequest 
    case isAddEventListenerRequest(message):
        return this.onAddIntentListenerRequest(message, sourceApp);
}
```

**Comment by Roaders** [comment]
Added the valid type predicates and sped up the normal predicate. Added some progress messages (generation is a bit slow). Added comments to type predicates.

**Comment by kriswest** [comment]
> @kriswest is the above valid typescript? I had never seen a switch statement like that (switching on the object then using type predicates for the cases). When I try it I get compile errors:

No its not valid - does narrow the type for you inside the cases, but doesn't make a correct comparison. My bad. A switch on message.type with the discriminated union and type strings in the cases should narrow the type inside the cases and check that the strings are valid - I'll test that later when back at my desk.

**Comment by kriswest** [comment]
> Hmmmm.... the diff is now huge... Could this just be because I deleted BrowserTypes and regenerated with the functions in a different order?

Its not that bad, looks to me mostly like the replacement union types, the is* functions and isValid* functions. The new functions LGTM based on a quick glance.

**Comment by Roaders** [comment]
> > Hmmmm.... the diff is now huge... Could this just be because I deleted BrowserTypes and regenerated with the functions in a different order?
> 
> Its not that bad, looks to me mostly like the replacement union types, the is* functions and isValid* functions. The new functions LGTM based on a quick glance.

I undid my changes to the file and just ran the type predicates script on it rather than generating from fresh.

**Review by kriswest — APPROVED** [review]
LGTM

**Comment by Roaders** [comment]
one of the checks is failing. what do I need to do to fixs that? is it test coverage?

**Comment by kriswest** [comment]
@Roaders theres a test failing due to a typing issue (somethign that may need an adjustment after your changes) and then something is up with the code coverage reporting. I'll take a look at the first issue and see if I can resolve. TO do that I'm going to merge this PR into branch on the FINOS repo and then open a new PR.

**Pull request merged**
