### PR TITLE
Adding a toolbox directory and the FDC3 Explained app

### PR DESCRIPTION
**Pull request by donbasuno**
Let the tooling project live long and prosper!

### CODE REVIEW

**Comment by rikoe** [comment]
@cla-bot check

**Comment by maoo** [comment]
@cla-bot check

**Comment by maoo** [comment]
@rikoe - I re-summoned the bot (again), as I validated that Chris was into our metadata; the PR is now labelled `cla-present` but the check is still failing. May I suggest to simply close this and create a new PR from the same branch, see if this fixes the issue?

Apologies for the inconvenience, never had a similar case before.

**Comment by rikoe** [comment]
Sure, thanks @maoo

**Pull request closed without merging**
