### PR TITLE
fix vulnerable deps in FDC3 workbench

### LINKED ISSUE #812: Resolve vulnerable dependencies in FDC3 workbench
### Use Case:
The current version of `react-scripts` has multiple vulns at the current version.

An attempt at updating to 5.0.1 broke the build.  Can we try recreating the project using the latest version of `create-react-app`?

### PR DESCRIPTION
**Pull request by kriswest**
resolves #812 

Overrides vulnerable dependencies to ensure a clean `npm audit`

### CODE REVIEW

**Comment by kriswest** [comment]
Hold on this, there's still an issue as the github action for website build is using old node versions and the website scripts use yarn one of both of which are causing the deps to be resolved differently which is breaking the website build. I'll have a look at those tomorrow and try again.

**Comment by kriswest** [comment]
@robmoffat It's working now - the website workflows should be based on npm now and FDC3 workbench comes back clean from an audit, build and fdc3-workbench app are both working. Hence, please check the output @robmoffat and let em know to merge. 

There are still vulnerabilities in the website and main project being reported, but this is a good first step. I'll look at the main project next. For the website... we might just have to go to docusaurus v2, which is on the todo list anyway.

**Comment by robmoffat** [comment]
I'm not sure how to test this without us first merging #808 
If we do that, we should be able to see the results of the scan in this PR.

**Comment by kriswest** [comment]
You can checkout the branch and npm audit the fdc3-workbench folder +
observe that the workflows ran on it ok (not including the scans from the
other pr not yet merged). I checked that the workbench it builds is working
ok already. That can be tested with the FDC3 chrome extension or
electron-fdc3 if necessary.

**Pull request merged**
