### PR TITLE
Fixing a build error introduced by quicktype enums

### PR DESCRIPTION
**Pull request by kriswest**
THe latest version of quicktype has started generating single value enums for constant values, which are causing issues in the context type tests (Context types serialize but cause type errors on deserialization). However, its also capable of generating const values - although this option hasn't been exposed correctly through the CLI  (raising a PR to fix). Generating true const value fixes the issue.

I hadn't noticed this test failing when I merged:
- #1082 
This PR is needed to get the build passing again - although we also need a quicktype release to make it repeatable

Also resolving a critical vulnerability (babel) via `npm audit fix`

### CODE REVIEW

**Comment by kriswest** [comment]
Apologies @hughtroeger @mattjamieson, looks like the last PR I merged broke the test (`npm run test`) this fixes them again.

**Comment by kriswest** [comment]
QuickType PR for exposing the prefer-const-values setting: https://github.com/glideapps/quicktype/pull/2426

To use a custom quicktype change s2tQuickTypeUtil.js to point `quicktypeExec` at the local version:

```js
// Normalise path to local quicktype executable.
const quicktypeExec = "node " + ["..","quicktype","dist","index.js"].join(path.sep);
//const quicktypeExec = ['.', 'node_modules', '.bin', 'quicktype'].join(path.sep);

const command = `${quicktypeExec} --prefer-const-values --no-combine-classes -s schema -o ${outputFile} ${sources}`;
```

Current version:
https://github.com/finos/FDC3/blob/d1273644eb41155013672edf17dc96e320f35826/s2tQuicktypeUtil.js#L43-L46

**Comment by kriswest** [comment]
THis has not fixed the issue as the package scripts are regenerating the context types during the build step. We'll either need to disable that or wait until Quick type merges the option to expose the `--prefer-const-values` setting...

**Comment by kriswest** [comment]
Ok, its passing now - as long as the types are not regenerated. Here's hoping quicktype merge that PR soon

**Review by hughtroeger — COMMENTED** [review]
Actually, why is there a `package-lock.json` change when the `package.json` doesn't have any changed dependencies? Is that intentional?

**Comment by kriswest** [comment]
> Actually, why is there a `package-lock.json` change when the `package.json` doesn't have any changed dependencies? Is that intentional?

`npm audit fix` did that. Its basically the same set of changes to resolve a critical vulnerability that dependabot wants to make in this PR: https://github.com/finos/FDC3/pull/1089
I'm not sure why it overrides the resolutions in the lock file rather than updating the package.json - but we can do that manually...

**Comment by kriswest** [comment]
@hughtroeger  its because is a transitive dependency, i.e. its coming in through tsdx, husky and jest:

```bash
PS C:\Users\Kris\Documents\code\FDC3> npm ls @babel/code-frame
@finos/fdc3@2.1.0-beta.3 C:\Users\Kris\Documents\code\FDC3
├─┬ husky@4.3.8
│ └─┬ cosmiconfig@7.1.0
│   └─┬ parse-json@5.2.0
│     └── @babel/code-frame@7.22.13 deduped
├─┬ jest-mock-extended@1.0.18
│ └─┬ jest@25.5.4
│   └─┬ @jest/core@25.5.4
│     └─┬ jest-message-util@25.5.0
│       └── @babel/code-frame@7.22.13 deduped
└─┬ tsdx@0.14.1
  ├─┬ @babel/core@7.21.4
  │ ├── @babel/code-frame@7.22.13
  │ └─┬ @babel/template@7.22.15
  │   └── @babel/code-frame@7.22.13 deduped
  ├─┬ @babel/traverse@7.23.2
  │ └── @babel/code-frame@7.22.13 deduped
  ├─┬ babel-eslint@10.1.0
  │ └── @babel/code-frame@7.22.13 deduped
  ├─┬ eslint@6.8.0
  │ └── @babel/code-frame@7.22.13 deduped
  └─┬ rollup-plugin-terser@5.3.1
    └── @babel/code-frame@7.22.13 deduped
``` 

It'll get sorted properly when we replace `tsdx` with something better maintained (see https://github.com/finos/FDC3/issues/1061)

**Comment by hughtroeger** [comment]
Ahh ok that makes sense. Looks good to me then.

**Review by mattjamieson — APPROVED** [review]
LGTM!

**Pull request merged**
