### PR TITLE
Update Scott Logic logo

### PR DESCRIPTION
**Pull request by joelwilliamsmith**

### CODE REVIEW

**Review by kriswest — APPROVED** [review]
@joelwilliamsmith @ColinEberhardt we'll need Joel to hit the [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/121826936/1184/#/?version=2) link from the EasyCLA notification to merge this, otherwise LGTM. Shout if you need any help.

**Review by bingenito — APPROVED** [review]

**Comment by ColinEberhardt** [comment]
Hi @kriswest - I've added @joelwilliamsmith to our 'corporate' CLA.

**Comment by kriswest** [comment]
@ColinEberhardt thanks, however @joelwilliamsmith will still need to pop back here and hit the <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/121826936/1184/#/?version=2' target='_blank'>Please click here to be authorized</a> link (here or in the EasyCLA comment). This time it should authorize him which will allow us to merge the PR. This only needs doing once, thereafter it should pick up his authorized status on future PRs.

Let us know if it fails to authorize (as that would indicate the wrong CLA was signed - FDC3 has a different one to other FINOS projects due to the Community Specification License)

**Review by hughtroeger — APPROVED** [review]

**Comment by kriswest** [comment]
@ColinEberhardt Closing due to inactivity. Presumably, you still want the change made, could someone recreate the PR? Otherwise re-open if you can get @joelwilliamsmith to hit the authorisation link in the EasyCLA comment.

**Pull request closed without merging**
