### PR TITLE
make chatInitSettings inherit from Context

### PR DESCRIPTION
**Pull request by Yannick-Symphony**
fixes https://github.com/finos/FDC3/issues/852

### CODE REVIEW

**Review by mistryvinay — APPROVED** [review]
Looks good to me.

**Comment by mistryvinay** [comment]
hi @Yannick-Symphony just one more update required for this PR.  Currently there is the use of the reserved word `public` in the schema.  This is causing issues when the schema is being built (#869)

`            "public": "boolean",`

Could we change this to something else, maybe `isPublic`?

**Comment by symphony-jean-michael** [comment]
Hi @mistryvinay 
It seems I already fixed the 'public' reserved word in the other PR https://github.com/finos/FDC3/pull/875 (Fixing bug https://github.com/finos/FDC3/issues/855)
So, there is no need to include it in this PR 😉 
(cc @Yannick-Symphony )

**Review by kriswest — APPROVED** [review]
LGTM

**Pull request merged**
