### PR TITLE
Add FDC3 training links.

### PR DESCRIPTION
**Pull request by TheJuanAndOnly99**
Preview of changes up [here](https://objective-lalande-1603d3.netlify.app/get-involved).

### CODE REVIEW

**Review by agitana — COMMENTED** [review]
LGTM, thank you @TheJuanAndOnly99!
@rikoe @kriswest we look forward to your feedback

**Review by kriswest — APPROVED** [review]
Looks good to me as a temporary  solution. We might replace the link at the top when creating the implementations page (see #466), which will allow us to provide some detail on the training and / or when we re-=organize the site (see #491)

**Comment by mindthegab** [comment]
@kriswest any reason why we can't merge this already? We are really starting to promote this.

Related, how do you guys feel to have also a reference to training in the Readme? If open to it, I can raise a PR.

**Comment by kriswest** [comment]
@mindthegab  Just in the habit of trying to get 2 reviews - but not really necessary for this, will merge.

**Pull request merged**
