### PR TITLE
Fdc3 web impl prettier + eslint

### PR DESCRIPTION
**Pull request by kriswest**
## Describe your change

Adds eslint into 5 of the mono repo projects and applies prettier across all projects the project. Prettier is set to run on a commit hook and eslint is configured to deal with prettier.

Prettier has been run on all source files.

### Related Issue
N/A

## Contributor License Agreement

- [x] I acknowledge that a contributor license agreement is required and that I have one in place or will seek to put one in place ASAP.

### CODE REVIEW

**Comment by kriswest** [comment]
@robmoffat if you're happy with this I'd like to get it merged before raising my PR, to cut the diff down. I'm about ready to do that (tests are all passing), although I have work to do on coverage (as you predicted).

**Comment by kriswest** [comment]
@robmoffat the 'CI Tests and Coverage' check is failing at the publishing stage (tests all passed). Its not the diff command failing (action doesn't know how to diff across a fork), but the publishing I think. Do you have any idea what its not liking? The PR coming from a fork?

**Comment by kriswest** [comment]
@robmoffat merged and checks running

**Comment by robmoffat** [comment]
Ok, so it's still not happy, but this time it's because it's trying to write the comment back.  

From my reading of the docs, this might not occur when this change to the GH action is merged into the main project: it's happening because you're on a remote branch.  

I suggest we merge it and we'll find out on your next PR if the docs are right.

**Review by robmoffat — APPROVED** [review]

**Pull request merged**
