### PR TITLE
Training Page

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by robmoffat** [comment]
[Training Page](https://deploy-preview-1095--fdc3.netlify.app/training)
[Community Changes](https://deploy-preview-1095--fdc3.netlify.app/community#type-examples-and-training)

**Review by kriswest — APPROVED** [review]
@robmoffat This looks good to me, my only suggestion would be to replace the use cases section on the FDC3 homepage with something about it, as those training materials do a much better job than the dusty old use cases do:

image

Say: 

**Getting Started with FDC3?**
[Intro to FDC3 image] [Developing with FDC3 image] [FDC3 certified developer image]

**Comment by kriswest** [comment]
If you take that suggestion feel free to merge this first and raise a new PR or add it it to it, up to you. 

THere are other links to the use cases so don't worry about them getting lost

**Comment by robmoffat** [comment]
It's a good suggestion - I'm going to raise as an issue because I think we should actually spend a bit more time overhauling that part of the site.

**Pull request merged**
