### PR TITLE
165 Add FDC3 Explained to the toolbox folder 

### LINKED ISSUE #165: FDC3 Explained - demo app for beginners?
Increasing adoption, improve documentation and create tooling projects are all part of our 2020 roadmap - and coming more from the business side - something I care very much about. I think we all have ideas and demo apps lying around but I wanted to start this issue to gather all our ideas and maybe even do a PR or two.

Demo Apps are great but they don't necessarily show the inner workings of FDC3:
- what is providing the API? 
- what channels are technically available?
- how can I easily send a broadcast from an external app to make sure that my app is working?
- and so on...

I therefore suggest that our first endeavor should a "toolbox" - basically a simple html/javascript page that can be loaded in any container or tool that provides an FDC3 API.

Page loaded in standard Chrome:

fdc3_explained_browser

Page loaded via manifest in OpenFin:

fdc3_explained_openfin

If possible we can host the page in our repo as well as manifest for running it in different environments. I created a working prototype but was not able to run it directly from GitHub - you will need to download the files:

Page: https://github.com/donbasuno/FDC3/blob/master/toolbox/fdc3_explained.html
OpenFin Manifest: https://github.com/donbasuno/FDC3/blob/master/toolbox/openfin/fdc3_explained.json

The code is not pretty (add a Men at Work gif and you are back in the 90s) but the basic broadcast works and can be tested against another demo app.

Please let me know your thoughts!

Thanks,

Johan

### PR DESCRIPTION
**Pull request by rikoe**
resolves #165 

I have recreated the FDC3 Explained pull request based on #367.

I have made the following changes:
- Rebased on latest master
- Move from website/static folder to toolbox/fdc3-explained
- Remove legacy version and demo apps
- Some renames and cleanup of files
- Improve handling of switching between different versions with drop-down
- Ensure that user informed no FDC3 version is detected when not running in a desktop agent
- Fix handling of OpenFin detection
- Use fdc3.getInfo for v1.2
- Add README.md
- Squashed commits to reduce churn

I believe if I did the build correctly, the deployment to the toolbox folder on the website should now also work, alongside that of FDC3 Workbench.

image

@kriswest I believe this addresses all your issues:

- [x] Ensure all files encapsulated in a folder under the 'toolbox' folder to ensure we can use it for other tools, i.e. toolbox/fdc3-explained
- [x] Rename the root page from toolbox/fdc3_explained.html to toolbox/fdc3-explained/index.html (and correct relative URLs in that file).
- [x] Also move toolbox/fdc3_explained_logo.svg -> toolbox/fdc3-explained/logo.svg
- [x] Remove duplicate files (including legacy.html)
- [x] Ensure that the 1.2 version uses the the fdc3.getInfo() function to get provider details - meaning vendor specific code can be removed
- [x] Remove vendor specific manifest files in toolbox/openfin directory
- [x] Add a Readme file to the toolbox/fdc3-explained folder

### CODE REVIEW

**Review by donbasuno — APPROVED** [review]
Looks good to me - ship it!

**Comment by kriswest** [comment]
Awaiting a few tweaks that are on a PR into Riko's branch. Will merge when those have been merged into this PR.

**Review by kriswest — CHANGES_REQUESTED** [review]
Awaiting a few tweaks that are on a PR into Riko's branch. Will merge when those have been merged into this PR.

**Review by kriswest — APPROVED** [review]
LGTM

**Pull request merged**
