### PR TITLE
remove union type for chat message

### PR DESCRIPTION
**Pull request by Yannick-Malins**
force the message part of a chat message to be a types structure, remove the union type that was kept for initial compatibility

update documentation

### CODE REVIEW

**Comment by kriswest** [comment]
@bingenito Heres a PR from @Yannick-Malins that will remove that union type, which was left in for backwards compatibility, but is likely not needed as this type was added in 2.1. If this looks good to you we'll confirm consent for it at the next SWG meeting and then merge it (and regenerate the typescript context types in the NPM module - currently a manual process due to a quicktype issue). 

I'll also see what we can do about adding a recommendation to not use union types in future.

**Comment by bingenito** [comment]
> (and regenerate the typescript context types in the NPM module - currently a manual process due to a quicktype issue).

Is it possible to see what the type will look like as part of the PR?

**Comment by kriswest** [comment]
This is the quicktype PR we're waiting on seeing merged so we can go back to automated generation: https://github.com/glideapps/quicktype/pull/2426
I've given them a nudge on it

**Comment by kriswest** [comment]
@bingenito I got access to the fork from @Yannick-Malins to regenerate the types, you can now see the change to ContextTypes.ts in the diff

**Comment by bingenito** [comment]
Thanks @kriswest and @Yannick-Malins, looks good.  I could have inferred that is the result but nice to see what gets generated up front.

**Comment by kriswest** [comment]
> Thanks @kriswest and @Yannick-Malins, looks good. I could have inferred that is the result but nice to see what gets generated up front.

Very true - feel free to bug the quicktype maintainers for me :-p

**Review by hughtroeger — APPROVED** [review]

**Review by bingenito — APPROVED** [review]

**Comment by kriswest** [comment]
@Yannick-Malins @mistryvinay can one of you hit that authorize link in the EasyCLA comment and check if you've got one of the new CLAs in place?

**Review by kriswest — APPROVED** [review]
LGTM

**Review by kriswest — CHANGES_REQUESTED** [review]
Needs a changelog entry

**Review by kriswest — APPROVED** [review]
LGTM

**Pull request merged**
