### PR TITLE
Singletrack Info

### PR DESCRIPTION
**Pull request by pauldyson**
Please add our info to the user directory

### CODE REVIEW

**Comment by pauldyson** [comment]
Easy CLS now signed; do you need the Pull Request to be resubmitted?

**Comment by kriswest** [comment]
Hi @pauldyson, no you shouldn't need to resubmit. It'll recheck your status with a further commit on the same branch. However, there may also be a command to trigger it which I'll find out about and get back to you.

**Review by kriswest — APPROVED** [review]
LGTM

**Comment by TheJuanAndOnly99** [comment]
Hi @pauldyson and @kriswest,

The reason @pauldyson is being blocked by EasyCLA is because there is no EasyCLA approval criteria set for the Singletrack CLA. To do this the CLA manager for Singletrack (in this case @pauldyson himself) needs to set the approval criterial that will determine who is covered under the Singletrack CLA. 

To set approval criteria the CLA manager can [log into the EasyCLA site](https://easycla.lfx.linuxfoundation.org/#/) (choose EasyCLA v2) and either:
- Add the GitHub usernames individually to the list of authorized contributors, or
- Add a corporate email domain, which authorizes anyone who has that email in their GitHub account, or
- Add a corporate GitHub Organization, where any member of the org is covered by the CLA.

Once this is done, you'll need to click the Details link in the PR (again) and click a button that acknowledges you want to be covered by the company.

Wait a little while for the check to re-run. Or comment "/easycla" to retrigger the bot.

Please let me know if you need further assistance.

**Comment by kriswest** [comment]
Thanks @TheJuanAndOnly99 and @pauldyson - I'll merge this shortly

**Comment by kriswest** [comment]
Change is live @pauldyson:
image

**Comment by pauldyson** [comment]
Excellent. Thanks @kriswest and @TheJuanAndOnly99

**Pull request merged**
