### PR TITLE
FDC3 workbench

### LINKED ISSUE #456: FDC3 Workbench - developer example application
### Use Case:
When developing an FDC3 integration one of the first things developers do is to implement a test application to try out the API calls and to give them something to test their actual application against. Such development is usually throw-away and includes only the bare minimum that they need. 

The FDC3 workbench is intended to replace such test apps by providing a ready-made 'workbench' application that makes it easy to create contexts, raise intents and work with channels, whilst also providing easy access to code snippets to replicate each action in your own implementation. The FDC3 Workbench may also be used as a reference implementation of a client application against which to test desktop agent implementations. 

By open-sourcing the app as part of the FDC3 repository a wider portion of the community can benefit from the workbench and will be able to participate in onward development & maintaince.

### Workflow Examples
- An app developer wishes to develop interop features for their app to:
  - **receive context** from other applications
    - The workbench application should allow you to: 
      - select and customize a context template or create a custom context object
      - join channels and broadcast that object
      - observe that their application receives and correctly handles the context 
  - **broadcast context** to other applications
    - The workbench application should allow you to: 
      - add listeners for both specific and all contexts
      - join channels
      - observe context objects received by each listener
  - **raise intents** for other applications to resolve
    - The workbench application should allow you to: 
      - select and customize a context template or create a custom context object
      - select or enter a custom intent
      - raise that intent via the desktop agent 
  - **listen for intents** raised by other applications
    - The workbench application should allow you to: 
      - select or enter a custom intent
      - add intent listeners for multiple events
      - observe context objects received by each intent listener
- A desktop developer wish to test the behaviour or their desktop agent implementation:
  - The workbench application should facilitate the use of as much of the FDC3 Desktop Agent API as possible, allowing the behaviour of desktop agents to be tested and compared to compliance information provided in the FDC3 specification.
      
### Additional Information
The FDC3 workbench is being contributed into the FDC3 repository to: 
- facilitate use by the widest possible portion of the FDC3 community
- encourage maintenance of the workbench application alongside the FDC3 standard itself, as the value of the workbench is dependent on compatibility with the standard.

The workbench will be added to a top-level /toolbox directory in the repository ('FDC3 Explained' is also being contributed to that directory, see #367)

### PR DESCRIPTION
**Pull request by kriswest**
Resolves #456 

## FDC3 Workbench 
A developer application for FDC3 implemented via [Create-React-App](https://create-react-app.dev/) and [Material-UI](https://mui.com/).

- Example hosted copy:  https://assets.finsemble.com/components/fdc3-workbench/
- Icon URL: https://assets.finsemble.com/components/fdc3-workbench/fdc3-icon-256.png

**Please Note:** 
- _a separate PR will deal with the deployment of the FDC3 workbench as part of the FDC3 website. The scope of this PR includes only the initial commit of the workbench itself._
- _This initial contribution provides a base UI implementation and works with the majority of FDC3 1.2's features._ 
  - _Implementing an additional panel for App channels is the primary TODO item listed in the Readme and will be undertaken in due course._

#### Work with System channels 
image

#### Create, save and broadcast templated contexts
image

#### Listen for context broadcasts
image

#### Raise intents
image

#### Receive intents and context
image

#### Copy code examples
image

#### View logs of FDC3 API interactions
image

#### No desktop agent API
image

### sample appD record:
(to be updated when deployed via FDC3 website)
```JSON
"FDC3 workbench": {
	"appId": "FDC3 workbench",
	"name": "FDC3 workbench",
	"description": "Development and test tool for FDC3 desktop agents and apps",
	"manifest": "<vendor specific manifest goes here>",
	"version": "1.0.0",
	"tooltip": "FDC3 Workbench",
	"images": [
		{
			"url": "https://assets.finsemble.com/components/fdc3-workbench/fdc3-icon-256.png",
			"tooltip": "FDC3 logo"
		}
	],
	"tags": ["fdc3", "interop", "interoperabilty", "developer tool"],
	"contactEmail": "info@cosaic.io",
	"supportEmail": "support@finsemble.com",
	"publisher": "Cosaic",
	"icons": [
		{
			"url": "https://assets.finsemble.com/components/fdc3-workbench/fdc3-icon-256.png"
		}
	]
}
```

### CODE REVIEW

**Review by mattjamieson — APPROVED** [review]
Awesome!

**Review by rikoe — COMMENTED** [review]
Should the binary files under website/static/toolbox all be checked in, or can they be generated at build time, and pushed to the GitHub pages branch, and then ignore? Adds quite a lot to the code base...

Otherwise looks good to me (apart from the extremely wide whitespace 😉 )

**Comment by kriswest** [comment]
@rikoe removed the built files. I haven't set up a .gitignore entry for them as I'm not sure if that will affect the publish to github pages... do you know how to set that up?

Re: whitespace, it's all indented with tabs, which is whats set in it's .prettierrc file...

**Review by rikoe — APPROVED** [review]
🎉

**Pull request merged**
