### PR TITLE
[Do not merge - CLA Check] FDC3 CLA contribution

### PR DESCRIPTION
**Pull request by hellosmithy**

### CODE REVIEW

**Comment by kriswest** [comment]
@hellosmithy When your firm has a CLA place do return here and hit the [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/121826936/1217/#/?version=2) link from the easycla comment and that will finish up the process of confirming you are covered by one

**Comment by hellosmithy** [comment]
@kriswest sorry it took a while, but CLA in place now 👍

**Comment by kriswest** [comment]
> @kriswest sorry it took a while, but CLA in place now 👍

No problem and glad to have you onboard!

**Pull request closed without merging**
